// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookApi")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", "bookApi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83cca844-1262-4d48-819c-0c93fc533075"),
                            Author = "Sonja Bogisich",
                            Category = "laborum",
                            Description = "Sed nisi velit perferendis dolore. Esse dolor vitae quae quod fuga. Voluptatem vitae est qui nihil placeat omnis. Quia natus aliquid voluptatum.",
                            Language = "aut",
                            Title = "quis quia sunt placeat non",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("2216b452-eca8-4cfb-aa75-be45cba9b61e"),
                            Author = "Sonja Bogisich",
                            Category = "ad",
                            Description = "Blanditiis sed cum. Repellat dolorem vitae esse soluta occaecati maiores.",
                            Language = "nihil",
                            Title = "odio ut eveniet corrupti officiis",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("a9d4512d-7b1e-4b65-80dd-75744b4faa71"),
                            Author = "Sonja Bogisich",
                            Category = "mollitia",
                            Description = "Praesentium esse reiciendis quia provident.",
                            Language = "non",
                            Title = "unde dolores blanditiis rerum aliquid",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("8e1f99e0-de76-44d2-848b-b760a660a4c9"),
                            Author = "Sonja Bogisich",
                            Category = "molestiae",
                            Description = "At quos id omnis dolorem reiciendis voluptatibus. Quibusdam hic impedit consequatur qui consequatur et incidunt accusamus cumque.",
                            Language = "corrupti",
                            Title = "numquam quo vero magni non",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("7361ef1a-0a08-4e38-9583-ea2570da0823"),
                            Author = "Sonja Bogisich",
                            Category = "iure",
                            Description = "Voluptate quia nesciunt et illo numquam. Explicabo est omnis itaque eos ipsa corporis. Velit modi omnis fugit.",
                            Language = "saepe",
                            Title = "natus corporis et laborum sit",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("f760a87b-ee57-457a-9fca-ee62795a00f8"),
                            Author = "Sonja Bogisich",
                            Category = "omnis",
                            Description = "Est provident neque sunt autem in occaecati animi reiciendis perspiciatis. Ut corrupti molestiae expedita quo consequatur accusantium quisquam. Ut nam consectetur repellendus aut tempore.",
                            Language = "pariatur",
                            Title = "necessitatibus delectus doloribus tenetur saepe",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("cd7e49e4-e677-4ed4-a2be-80b9bac28f3a"),
                            Author = "Sonja Bogisich",
                            Category = "commodi",
                            Description = "Modi id dolor quo. Est natus eius quis et similique vitae commodi nemo. Delectus consequatur reprehenderit ut ut.",
                            Language = "quo",
                            Title = "porro ex ullam sed in",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("4ba85777-f4ad-4dff-87cb-2ed1a2fe646b"),
                            Author = "Sonja Bogisich",
                            Category = "quidem",
                            Description = "Excepturi numquam tempore earum sunt qui delectus. Magnam quia et sit.",
                            Language = "qui",
                            Title = "nisi eaque rerum perferendis aut",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("35777745-8c78-4bc0-a610-68622c3d0945"),
                            Author = "Sonja Bogisich",
                            Category = "velit",
                            Description = "Ea iusto repellendus voluptas maiores dignissimos aspernatur necessitatibus rerum deserunt.",
                            Language = "excepturi",
                            Title = "qui unde quia ratione ea",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("20a59a8c-8ac0-4bdd-8c58-775679724a78"),
                            Author = "Sonja Bogisich",
                            Category = "modi",
                            Description = "Fuga laudantium aut. Accusantium aliquam iusto repudiandae perspiciatis excepturi ullam id consectetur. Sint optio accusamus dolorem aut provident et quibusdam. Eveniet sequi maiores repellat qui rerum dicta explicabo doloremque.",
                            Language = "nihil",
                            Title = "architecto at iure accusamus ipsa",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("874eeea7-e9a5-4823-92c0-ad46d0dd3e2a"),
                            Author = "Sonja Bogisich",
                            Category = "itaque",
                            Description = "Sed accusantium saepe qui consectetur. Suscipit dolor magnam ut cupiditate tenetur nemo.",
                            Language = "et",
                            Title = "fugiat aspernatur sed eveniet tempora",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("9af61d96-4438-42e0-80af-309e0ef7f781"),
                            Author = "Sonja Bogisich",
                            Category = "aliquid",
                            Description = "Consequuntur deleniti tempore ea. Facere similique aliquam mollitia et sit dolor sed autem et. Molestiae ut repellat voluptas.",
                            Language = "veniam",
                            Title = "maxime veritatis hic mollitia nobis",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("017a7277-432e-408e-81b1-f5871fcf84d7"),
                            Author = "Sonja Bogisich",
                            Category = "repudiandae",
                            Description = "Qui accusantium ducimus dolor deserunt ut. Possimus beatae nulla voluptatibus numquam qui hic facilis quia dicta.",
                            Language = "veniam",
                            Title = "odio ducimus aut consequatur inventore",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("6569fc28-ac5d-4723-bd4f-ebf21b18c947"),
                            Author = "Sonja Bogisich",
                            Category = "quibusdam",
                            Description = "Adipisci enim quia veritatis debitis dicta reprehenderit exercitationem iure reiciendis.",
                            Language = "et",
                            Title = "maiores perspiciatis dolor rerum tempora",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("e08e1147-8008-44af-a543-b2acbf8c2d44"),
                            Author = "Sonja Bogisich",
                            Category = "aut",
                            Description = "Pariatur qui cumque autem dicta eligendi. Deleniti hic ullam porro neque deleniti doloribus quo aut dolor. Omnis possimus rerum esse. Sapiente magnam provident sint aut qui voluptatum sint reiciendis est.",
                            Language = "necessitatibus",
                            Title = "dolor accusamus officia eum voluptatem",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("51260475-0699-4a79-84a0-f6efe62e189c"),
                            Author = "Sonja Bogisich",
                            Category = "illo",
                            Description = "Perspiciatis sint harum sequi voluptatem sed accusamus cupiditate ut. Accusamus molestiae assumenda ut.",
                            Language = "officia",
                            Title = "vitae aspernatur quis ab est",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("a2d9f35d-c984-47ab-a2ba-46abb74935aa"),
                            Author = "Sonja Bogisich",
                            Category = "repudiandae",
                            Description = "Enim velit voluptatum et consequatur voluptatem hic. Beatae ut sed eveniet possimus.",
                            Language = "sit",
                            Title = "at ea tenetur ipsum eius",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("af22d0ee-12e4-4cb9-b082-efb80be5aa1f"),
                            Author = "Sonja Bogisich",
                            Category = "quos",
                            Description = "Esse dolorem quibusdam perferendis laudantium. Deserunt ut optio ea aut. Aut odit et quae.",
                            Language = "labore",
                            Title = "reprehenderit quis pariatur dolor eius",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("560419a7-1527-4d0e-90f0-ef9f010923e8"),
                            Author = "Sonja Bogisich",
                            Category = "soluta",
                            Description = "Accusamus aspernatur nesciunt commodi eos quo quas voluptatem aut. Illum quae delectus et est. Non commodi quas.",
                            Language = "eos",
                            Title = "sit quasi dolores pariatur veniam",
                            TotalPages = 0
                        },
                        new
                        {
                            Id = new Guid("31db715b-1a95-4604-a9f6-90f33c152309"),
                            Author = "Sonja Bogisich",
                            Category = "voluptatem",
                            Description = "Aspernatur quaerat et reprehenderit doloremque consequuntur dolores minima. Et voluptatem et fugiat dolorum nobis qui fuga unde rem. Quis commodi natus ea maiores. Qui sunt itaque in.",
                            Language = "dolor",
                            Title = "non quos temporibus velit temporibus",
                            TotalPages = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
